openapi: 3.0.4
info:
  title: Todo API
  version: v1
paths:
  '/api/todolists/{listId}/todoitems':
    get:
      tags:
        - TodoItems
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItemDto'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItemDto'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItemDto'
    post:
      tags:
        - TodoItems
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoItem'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateTodoItem'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateTodoItem'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
            text/json:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
  '/api/todolists/{listId}/todoitems/{id}':
    get:
      tags:
        - TodoItems
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
            text/json:
              schema:
                $ref: '#/components/schemas/TodoItemDto'
    put:
      tags:
        - TodoItems
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoItem'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoItem'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateTodoItem'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - TodoItems
      parameters:
        - name: listId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/todolists:
    get:
      tags:
        - TodoLists
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoListDto'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoListDto'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoListDto'
    post:
      tags:
        - TodoLists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoList'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateTodoList'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateTodoList'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TodoList'
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
            text/json:
              schema:
                $ref: '#/components/schemas/TodoList'
  '/api/todolists/{id}':
    get:
      tags:
        - TodoLists
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TodoListDto'
            application/json:
              schema:
                $ref: '#/components/schemas/TodoListDto'
            text/json:
              schema:
                $ref: '#/components/schemas/TodoListDto'
    put:
      tags:
        - TodoLists
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoList'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoList'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateTodoList'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - TodoLists
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
components:
  schemas:
    CreateTodoItem:
      required:
        - title
      type: object
      properties:
        title:
          minLength: 1
          type: string
        description:
          type: string
          nullable: true
        completed:
          type: boolean
          nullable: true
      additionalProperties: false
    CreateTodoList:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          nullable: true
      additionalProperties: false
    TodoItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        completed:
          type: boolean
        todoListId:
          type: integer
          format: int64
        todoList:
          $ref: '#/components/schemas/TodoList'
      additionalProperties: false
    TodoItemDto:
      required:
        - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        completed:
          type: boolean
      additionalProperties: false
    TodoList:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        todoItems:
          type: array
          items:
            $ref: '#/components/schemas/TodoItem'
          nullable: true
      additionalProperties: false
    TodoListDto:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
      additionalProperties: false
    UpdateTodoItem:
      type: object
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        completed:
          type: boolean
          nullable: true
      additionalProperties: false
    UpdateTodoList:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          nullable: true
      additionalProperties: false